<?php

namespace App\Livewire;

use App\Models\Patient;
use App\Models\Child;
use Livewire\Component;
use Illuminate\Validation\Rule;

class ChildRegistration extends Component
{
    // Search for mother
    public $searchTerm = '';
    public $searchResults = [];
    public $selectedMother = null;

    // Child data
    public $patient_id = null;
    public $nik = '';
    public $name = '';
    public $gender = '';
    public $dob = '';
    public $pob = '';
    public $birth_weight = '';
    public $birth_height = '';

    // UI state
    public $showSuccess = false;
    public $savedChildId = null;

    protected function rules()
    {
        return [
            'patient_id' => 'required|exists:patients,id',
            'nik' => [
                'nullable',
                'digits:16',
                Rule::unique('children', 'nik'),
            ],
            'name' => 'required|string|max:255',
            'gender' => 'required|in:L,P',
            'dob' => 'required|date|before_or_equal:today',
            'pob' => 'nullable|string|max:255',
            'birth_weight' => 'nullable|numeric|min:500|max:10000', // gram
            'birth_height' => 'nullable|numeric|min:20|max:100', // cm
        ];
    }

    protected $messages = [
        'patient_id.required' => 'Ibu harus dipilih terlebih dahulu',
        'patient_id.exists' => 'Data ibu tidak ditemukan',
        'nik.digits' => 'NIK harus 16 digit',
        'nik.unique' => 'NIK sudah terdaftar',
        'name.required' => 'Nama anak wajib diisi',
        'gender.required' => 'Jenis kelamin wajib dipilih',
        'dob.required' => 'Tanggal lahir wajib diisi',
        'dob.before_or_equal' => 'Tanggal lahir tidak boleh di masa depan',
        'birth_weight.min' => 'Berat badan lahir minimal 500 gram',
        'birth_weight.max' => 'Berat badan lahir maksimal 10000 gram',
        'birth_height.min' => 'Tinggi badan lahir minimal 20 cm',
        'birth_height.max' => 'Tinggi badan lahir maksimal 100 cm',
    ];

    public function updatedSearchTerm()
    {
        if (strlen($this->searchTerm) >= 3) {
            $this->searchResults = Patient::where(function($query) {
                $query->where('name', 'like', '%' . $this->searchTerm . '%')
                      ->orWhere('phone', 'like', '%' . $this->searchTerm . '%')
                      ->orWhere('nik', 'like', '%' . $this->searchTerm . '%');
            })
            ->limit(10)
            ->get();
        } else {
            $this->searchResults = [];
        }
    }

    public function selectMother($patientId)
    {
        $this->selectedMother = Patient::findOrFail($patientId);
        $this->patient_id = $patientId;
        $this->searchResults = [];
        $this->searchTerm = '';
    }

    public function clearMotherSelection()
    {
        $this->selectedMother = null;
        $this->patient_id = null;
    }

    public function submit()
    {
        $validatedData = $this->validate();

        // No need to manually generate no_rm - trait handles it automatically
        // Create child record
        $child = Child::create([
            'patient_id' => $this->patient_id,
            'nik' => $this->nik ?: null,
            // 'no_rm' will be auto-generated by GeneratesChildRm trait
            'name' => $this->name,
            'gender' => $this->gender,
            'dob' => $this->dob,
            'pob' => $this->pob,
            'birth_weight' => $this->birth_weight ?: null,
            'birth_height' => $this->birth_height ?: null,
            'status' => 'Hidup',
        ]);

        $this->showSuccess = true;
        $this->savedChildId = $child->id;

        session()->flash('success', "Anak {$child->name} berhasil didaftarkan dengan No. RM: {$child->no_rm}!");
    }

    public function render()
    {
        $nextNoRm = Child::getNextRmNumber();
        return view('livewire.child-registration', [
            'nextNoRm' => $nextNoRm,
        ]);
    }
}
